# -*- coding: utf-8 -*-
"""Handwritten_Digit_Recognition_using_Random_Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5FX1hloJ7UdvTfdbuc7oyVR2yXu1fCm
"""

import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay
)

digits = load_digits()

print("Dataset Loaded Successfully!")

print("Shape of Images:", digits.images.shape)
print("Shape of Data:", digits.data.shape)
print("Shape of Target:", digits.target.shape)

print("\nClasses:")
print(np.unique(digits.target))

plt.figure(figsize=(10,5))

for i in range(10):
    plt.subplot(2,5,i+1)
    plt.imshow(digits.images[i], cmap='gray')
    plt.title(f"Label: {digits.target[i]}")
    plt.axis('off')

plt.tight_layout()
plt.show()

X = digits.data
y = digits.target

print("Features Shape:", X.shape)
print("Labels Shape:", y.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Samples:", X_train.shape[0])
print("Testing Samples:", X_test.shape[0])

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

print("Model Training Completed!")

y_pred = rf_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", round(accuracy * 100, 2), "%")

print("\nClassification Report:\n")

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm
)

disp.plot(cmap='Blues')

plt.title("Confusion Matrix")
plt.show()

plt.figure(figsize=(12,6))

for i in range(12):
    plt.subplot(3,4,i+1)

    plt.imshow(
        X_test[i].reshape(8,8),
        cmap='gray'
    )

    plt.title(
        f"Pred: {y_pred[i]}\nActual: {y_test[i]}"
    )

    plt.axis('off')

plt.tight_layout()
plt.show()

sample_index = 25

sample_image = X_test[sample_index].reshape(8,8)

prediction = rf_model.predict(
    [X_test[sample_index]]
)

plt.imshow(sample_image, cmap='gray')
plt.title(f"Predicted Digit: {prediction[0]}")
plt.axis('off')
plt.show()

print("Predicted Digit:", prediction[0])
print("Actual Digit:", y_test[sample_index])

import pandas as pd

feature_importance = rf_model.feature_importances_

print("Number of Features:", len(feature_importance))

plt.figure(figsize=(10,5))
plt.plot(feature_importance)
plt.title("Feature Importance")
plt.xlabel("Pixel Number")
plt.ylabel("Importance")
plt.show()

import joblib

joblib.dump(
    rf_model,
    "digit_recognition_random_forest.pkl"
)

print("Model Saved Successfully!")

loaded_model = joblib.load(
    "digit_recognition_random_forest.pkl"
)

prediction = loaded_model.predict(
    [X_test[0]]
)

print("Prediction:", prediction[0])

